repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v21.1.2
  hooks:
    - id: clang-format
      types_or: [c, c++, header]
- repo: local
  hooks:
    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy
      language: system
      files: ^(include|src|tests)/.*\.(h|cpp)$
      types_or: [c, c++, header]
      args: [-p, build/ninja-multi-vcpkg, --config-file=.clang-tidy]
      require_serial: true
