load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_package_metadata = ["//:license"])

cc_test(
    name = "warp_test",
    srcs = [
        "mqtt/client_test.cpp",
        "mqtt/codec_test.cpp",
        "mqtt/message_test.cpp",
        "mqtt/server_test.cpp",
        "warp_test.cpp",
    ],
    deps = [
        "//:warp",
        "@googletest//:gtest_main",
    ],
)
