# test.yml

name: test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: lukka/run-vcpkg@v11
      - run: |
          cmake --preset ninja-multi-vcpkg
          cmake --build --preset test
          ctest --test-dir build/test --output-on-failure
