# test.yml

name: test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: |
          cmake --preset ninja-multi-vcpkg
          uvx pre-commit run --all-files --show-diff-on-failure
          cmake --build --preset test
          ctest --preset test
